### ISSUE TITLE
some issue and recommnedations

### ISSUE THREAD

**Issue by malmi315** [ElectroTechnique/TSynth-for-Teensy3.6#4]
Hi I love yopur project.

I upload your code to a teensy 3.6,  and made a controller for it.
Sounds good !
I have some things I would love :

1-Exponential envelopes instead of linear ( I think it´s a must , linears are so unmusicall )
2-When I add resonance, distortion in the sound are very audible. Maybe some compensation like what you ear on analog gear ( when you turn resonance, volumen drops) anyway I think gain pad need to be tamed. Seems need more headroom ( there is a lot of distortion when in more than a half volumen).
3-A midi command to save a patch remotely thru midi would awesome.
4-add another CC to control Pitch Lfo ammount ( so you can save  a "fixed lfo pitched" patch)
5-add another CC to control CC1 to lfo-pitch amount  ( so you can use your controler mod wheel to subtle lfo>pitch a sound)
6-Add velocity to amp ammount with another CC
7-Add velocity to filter ammout with another CC
8-Add a master volume parameter per patch
9-Glide is acting strange ... ( pitch is not comming from the last played note  )
10-Adding a delay FX could be wonderfull
Cheers !
thanks ! 
Marcelo Malmierca

**Comment by Electrotechnique** [comment]
Thanks for the suggestions.
1. This is in the PJRC Audio Library and for someone else to work on.
2. Yes, could be fine tuned.
3. But all patches would be called 'Initial patch'
4. It's CC 3
5. Mod wheel amount? This is set in Settings
6. Yes, probably next.
7. Possibly with 6.
8. I can see why this is useful, but volume (which is the DAC volume) should be a global thing.
9. I'm not convinced by it either and it needs more work.
10. Too CPU intensive for T3.6
